import type { EntitlementPayload } from '../types';

/**
 * Broad catalog of Adobe products and entry points commonly assignable from Admin Console,
 * plus public app and marketing URLs. Your org’s purchasable SKUs and labels may differ;
 * this is not a live mirror of Adobe’s product registry.
 *
 * @see https://adminconsole.adobe.com/
 * @see https://www.adobe.com/creativecloud/all-apps.html
 */
export const ADOBE_ENTITLEMENTS: EntitlementPayload[] = [
    // --- Administration, shell, and learning ---
    {
        id: 'adobe-admin-console',
        title: 'Adobe Admin Console',
        description: 'Manage users, licenses, and products for your organization.',
        href: 'https://adminconsole.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-developer-console',
        title: 'Adobe Developer Console',
        description: 'Create projects, credentials, and APIs on Adobe I/O.',
        href: 'https://developer.adobe.com/console',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-cloud',
        title: 'Adobe Experience Cloud',
        description: 'Experience Cloud home — launch apps and solutions.',
        href: 'https://experience.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-league',
        title: 'Adobe Experience League',
        description: 'Tutorials, courses, and documentation for Adobe products.',
        href: 'https://experienceleague.adobe.com/',
        openMode: 'new-tab',
    },

    // --- Creative Cloud & collaboration ---
    {
        id: 'adobe-creative-cloud',
        title: 'Adobe Creative Cloud',
        description: 'Install and manage Creative Cloud desktop apps.',
        href: 'https://creativecloud.adobe.com/apps/all/desktop',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-express',
        title: 'Adobe Express',
        description: 'Create graphics, photos, and videos quickly.',
        href: 'https://new.express.adobe.com/?showIntentQuiz=false&locale=en-US',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-firefly',
        title: 'Adobe Firefly',
        description: 'Generative AI for images and more.',
        href: 'https://firefly.adobe.com/?promoid=L3XTTKDX&locale=en-US&mv=other&mv2=tab',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-frame-io',
        title: 'Frame.io',
        description: 'Video review, collaboration, and shared workspaces.',
        href: 'https://www.adobe.com/creativecloud/business/frameio.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-photoshop',
        title: 'Adobe Photoshop',
        description: 'Image editing and design.',
        href: 'https://photoshop.adobe.com/?promoid=LCDWT9XV&lang=en&mv=other&mv2=tab',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-illustrator',
        title: 'Adobe Illustrator',
        description: 'Vector graphics and illustration.',
        href: 'https://illustrator.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-indesign',
        title: 'Adobe InDesign',
        description: 'Layout and publishing for print and digital.',
        href: 'https://www.adobe.com/products/indesign.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-acrobat',
        title: 'Adobe Acrobat',
        description: 'PDFs and documents.',
        href: 'https://acrobat.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-premiere-pro',
        title: 'Adobe Premiere Pro',
        description: 'Professional video editing.',
        href: 'https://www.adobe.com/products/premiere.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-after-effects',
        title: 'Adobe After Effects',
        description: 'Motion graphics and visual effects.',
        href: 'https://www.adobe.com/products/aftereffects.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-audition',
        title: 'Adobe Audition',
        description: 'Audio recording, editing, and mixing.',
        href: 'https://www.adobe.com/products/audition.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-animate',
        title: 'Adobe Animate',
        description: 'Animation for web, TV, and games.',
        href: 'https://www.adobe.com/products/animate.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-dreamweaver',
        title: 'Adobe Dreamweaver',
        description: 'Web design and development.',
        href: 'https://www.adobe.com/products/dreamweaver.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-lightroom',
        title: 'Adobe Photoshop Lightroom',
        description: 'Cloud-based photo editing and organization.',
        href: 'https://www.adobe.com/products/photoshop-lightroom.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-lightroom-classic',
        title: 'Adobe Lightroom Classic',
        description: 'Desktop-focused photo workflow and editing.',
        href: 'https://www.adobe.com/products/photoshop-lightroom-classic.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-bridge',
        title: 'Adobe Bridge',
        description: 'Central hub for creative assets and metadata.',
        href: 'https://www.adobe.com/products/bridge.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-character-animator',
        title: 'Adobe Character Animator',
        description: 'Real-time animation for characters.',
        href: 'https://www.adobe.com/products/character-animator.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-media-encoder',
        title: 'Adobe Media Encoder',
        description: 'Ingest, transcode, and export media.',
        href: 'https://www.adobe.com/products/media-encoder.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-premiere-rush',
        title: 'Adobe Premiere Rush',
        description: 'Create and share video on the go.',
        href: 'https://www.adobe.com/products/premiere-rush.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-fresco',
        title: 'Adobe Fresco',
        description: 'Drawing and painting across tablet and desktop.',
        href: 'https://www.adobe.com/products/fresco.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-aero',
        title: 'Adobe Aero',
        description: 'Design and share augmented reality experiences.',
        href: 'https://www.adobe.com/products/aero.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-substance-3d',
        title: 'Adobe Substance 3D',
        description: '3D materials, texturing, and staging.',
        href: 'https://www.adobe.com/products/substance3d.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-xd',
        title: 'Adobe XD',
        description: 'UX/UI design and prototyping.',
        href: 'https://www.adobe.com/products/xd.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-stock',
        title: 'Adobe Stock',
        description: 'Royalty-free images, video, audio, and templates.',
        href: 'https://stock.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-fonts',
        title: 'Adobe Fonts',
        description: 'Typefaces for web and desktop creative work.',
        href: 'https://fonts.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-color',
        title: 'Adobe Color',
        description: 'Color themes, accessibility checks, and gradients.',
        href: 'https://color.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-behance',
        title: 'Behance',
        description: 'Showcase and discover creative work.',
        href: 'https://www.behance.net/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-portfolio',
        title: 'Adobe Portfolio',
        description: 'Build a custom creative portfolio website.',
        href: 'https://portfolio.adobe.com/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-photoshop-elements',
        title: 'Adobe Photoshop Elements',
        description: 'Photo editing for enthusiasts.',
        href: 'https://www.adobe.com/products/photoshop-elements.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-premiere-elements',
        title: 'Adobe Premiere Elements',
        description: 'Video editing for enthusiasts.',
        href: 'https://www.adobe.com/products/premiere-elements.html',
        openMode: 'new-tab',
    },

    // --- Document Cloud ---
    {
        id: 'adobe-document-cloud',
        title: 'Adobe Document Cloud',
        description: 'Acrobat, e-signatures, and document automation.',
        href: 'https://www.adobe.com/documentcloud.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-acrobat-sign',
        title: 'Adobe Acrobat Sign',
        description: 'Legally binding e-signatures and workflows.',
        href: 'https://www.adobe.com/sign.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-digital-editions',
        title: 'Adobe Digital Editions',
        description: 'Read and manage eBooks and digital publications.',
        href: 'https://www.adobe.com/solutions/ebook/digital-editions/download.html',
        openMode: 'new-tab',
    },

    // --- Experience Cloud & marketing ---
    {
        id: 'adobe-ai-llms-agents',
        title: 'Adobe AI — LLMs and agents',
        description: 'Enterprise AI, models, and agent capabilities across Adobe solutions.',
        href: 'https://business.adobe.com/artificial-intelligence.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-advertising',
        title: 'Adobe Advertising',
        description: 'Plan, buy, measure, and optimize advertising.',
        href: 'https://business.adobe.com/products/advertising/adobe-advertising-cloud.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-analytics',
        title: 'Adobe Analytics',
        description: 'Digital analytics, reporting, and customer intelligence.',
        href: 'https://business.adobe.com/products/analytics/adobe-analytics.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-audience-manager',
        title: 'Adobe Audience Manager',
        description: 'Data management platform for audience segmentation and activation.',
        href: 'https://business.adobe.com/products/audience-manager/adobe-audience-manager.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-campaign',
        title: 'Adobe Campaign',
        description: 'Cross-channel campaign management and orchestration.',
        href: 'https://business.adobe.com/products/campaign/adobe-campaign.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-commerce',
        title: 'Adobe Commerce',
        description: 'Flexible B2B and B2C commerce experiences.',
        href: 'https://business.adobe.com/products/commerce.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-customer-journey-analytics',
        title: 'Adobe Customer Journey Analytics',
        description: 'Cross-channel journey analysis on Experience Platform.',
        href: 'https://business.adobe.com/products/customer-journey-analytics/adobe-customer-journey-analytics.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-manager',
        title: 'Adobe Experience Manager',
        description: 'AEM — content and digital experience management.',
        href: 'https://business.adobe.com/products/experience-manager/adobe-experience-manager.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-manager-assets',
        title: 'Adobe Experience Manager Assets',
        description: 'Enterprise DAM and rich media delivery.',
        href: 'https://business.adobe.com/products/experience-manager/assets.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-aem-brand-portal',
        title: 'AEM Brand Portal',
        description: 'Distribute approved brand and marketing assets to partners.',
        href: 'https://business.adobe.com/products/experience-manager/assets/brand-portal.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-manager-forms',
        title: 'Adobe Experience Manager Forms',
        description: 'Adaptive forms, communications, and workflows.',
        href: 'https://business.adobe.com/products/experience-manager/forms.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-manager-guides',
        title: 'Adobe Experience Manager Guides',
        description: 'DITA and structured content for documentation.',
        href: 'https://business.adobe.com/products/experience-manager/guides.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-manager-screens',
        title: 'Adobe Experience Manager Screens',
        description: 'Digital signage and in-venue experiences.',
        href: 'https://business.adobe.com/products/experience-manager/screens.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-manager-sites',
        title: 'Adobe Experience Manager Sites',
        description: 'Websites, pages, and omnichannel web experiences.',
        href: 'https://business.adobe.com/products/experience-manager/sites.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-experience-platform',
        title: 'Adobe Experience Platform',
        description: 'AEP — customer data platform, profiles, and activation.',
        href: 'https://business.adobe.com/products/experience-platform/adobe-experience-platform.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-genstudio',
        title: 'Adobe GenStudio',
        description: 'Generative AI for content creation and campaign workflows.',
        href: 'https://business.adobe.com/products/genstudio/adobe-genstudio.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-journey-optimizer',
        title: 'Adobe Journey Optimizer',
        description: 'Orchestrate real-time customer journeys across channels.',
        href: 'https://business.adobe.com/products/journey-optimizer/adobe-journey-optimizer.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-learning-manager',
        title: 'Adobe Learning Manager',
        description: 'LMS for customer, partner, and employee learning.',
        href: 'https://business.adobe.com/products/learning-manager/adobe-learning-manager.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-marketo-engage',
        title: 'Adobe Marketo Engage',
        description: 'B2B marketing automation and lead management.',
        href: 'https://business.adobe.com/products/marketo.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-marketo-measure',
        title: 'Adobe Marketo Measure',
        description: 'Multi-touch attribution and marketing performance.',
        href: 'https://business.adobe.com/products/marketo/marketo-measure.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-mix-modeler',
        title: 'Adobe Mix Modeler',
        description: 'Marketing mix modeling and unified measurement.',
        href: 'https://business.adobe.com/products/mix-modeler.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-real-time-cdp',
        title: 'Adobe Real-Time CDP',
        description: 'Real-time customer profiles and activation.',
        href: 'https://business.adobe.com/products/real-time-customer-data-platform.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-target',
        title: 'Adobe Target',
        description: 'A/B testing, personalization, and optimization.',
        href: 'https://business.adobe.com/products/target/adobe-target.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-workfront',
        title: 'Adobe Workfront',
        description: 'Work management for marketing and creative teams.',
        href: 'https://business.adobe.com/products/workfront/adobe-workfront.html',
        openMode: 'new-tab',
    },

    // --- Platform & extensibility ---
    {
        id: 'adobe-app-builder',
        title: 'Adobe App Builder',
        description: 'Build Experience Cloud apps and UI extensions on Adobe I/O.',
        href: 'https://developer.adobe.com/app-builder/docs/overview/',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-io-runtime',
        title: 'Adobe I/O Runtime',
        description: 'Serverless actions and APIs on Adobe I/O.',
        href: 'https://developer.adobe.com/runtime/docs/',
        openMode: 'new-tab',
    },

    // --- Learning, web conferencing, and technical publishing ---
    {
        id: 'adobe-captivate',
        title: 'Adobe Captivate',
        description: 'Author eLearning courses and simulations.',
        href: 'https://www.adobe.com/products/captivate.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-connect',
        title: 'Adobe Connect',
        description: 'Webinars, virtual classrooms, and online meetings.',
        href: 'https://www.adobe.com/products/adobeconnect.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-coldfusion',
        title: 'Adobe ColdFusion',
        description: 'Rapid web application development platform.',
        href: 'https://www.adobe.com/products/coldfusion-family.html',
        openMode: 'new-tab',
    },
    {
        id: 'adobe-robohelp',
        title: 'Adobe RoboHelp',
        description: 'Help systems, policies, and knowledge bases.',
        href: 'https://www.adobe.com/products/robohelp.html',
        openMode: 'new-tab',
    },
];
